// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppSoundSetting: typeof import('./components/AppSoundSetting.vue')['default']
    AppTaskSetting: typeof import('./components/AppTaskSetting.vue')['default']
    IntegrationTodoistInfoDialog: typeof import('./components/IntegrationTodoistInfoDialog.vue')['default']
    IntegrationWebhookInfoDialog: typeof import('./components/IntegrationWebhookInfoDialog.vue')['default']
    NotificationMobileInfoDialog: typeof import('./components/NotificationMobileInfoDialog.vue')['default']
    PremiumDialog: typeof import('./components/PremiumDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialogIntegration: typeof import('./components/SettingsDialogIntegration.vue')['default']
    SettingsDialogNotification: typeof import('./components/SettingsDialogNotification.vue')['default']
    SettingsDialogSound: typeof import('./components/SettingsDialogSound.vue')['default']
    SettingsDialogTask: typeof import('./components/SettingsDialogTask.vue')['default']
    SettingsDialogTheme: typeof import('./components/SettingsDialogTheme.vue')['default']
    SettingsDialogTimer: typeof import('./components/SettingsDialogTimer.vue')['default']
    TasksDialog: typeof import('./components/TasksDialog.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheSettingsDialog: typeof import('./components/TheSettingsDialog.vue')['default']
    TheTasks: typeof import('./components/TheTasks.vue')['default']
  }
}
