// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppIntegrationSetting: typeof import('./components/AppIntegrationSetting.vue')['default']
    AppNotificationSetting: typeof import('./components/AppNotificationSetting.vue')['default']
    AppSoundSetting: typeof import('./components/AppSoundSetting.vue')['default']
    AppTaskSetting: typeof import('./components/AppTaskSetting.vue')['default']
    AppThemeSetting: typeof import('./components/AppThemeSetting.vue')['default']
    AppTimerSetting: typeof import('./components/AppTimerSetting.vue')['default']
    MobileAlarmDialog: typeof import('./components/MobileAlarmDialog.vue')['default']
    PremiumDialog: typeof import('./components/PremiumDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    TheSettingsDialog: typeof import('./components/TheSettingsDialog.vue')['default']
    TodoistDialog: typeof import('./components/TodoistDialog.vue')['default']
    WebhookDialog: typeof import('./components/WebhookDialog.vue')['default']
  }
}
